name: Build Dist

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/bun-action@v2
        with:
          bun-version: stable

      - name: Install dependencies
        run: bun install

      - name: Build dist files
        run: bun run build-all

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
